"""
models/moderation_intelligence.py — Ported from Moo-assistant's
bot/database/models_moderation_intel.py (ModerationReport, ModerationAnalysis,
StaffEscalation only - Investigation/InvestigationFinding live in
models/investigation.py, and the reference-data tables (KnownIssue,
LinkedAccount, WhitelistEntry) live in models/knowledge.py, matching this
project's per-domain file convention rather than Moo's single models file).

Two deliberate adaptations from the source, not a verbatim port:

1. Every `guild_id` column is dropped. Moo is designed to potentially serve
   multiple Discord guilds from one bot process; umbrella-core has no
   multi-tenant concept anywhere - one deployment serves one Discord
   community, and RBAC/users/everything else is already global, not
   guild-scoped. Keeping guild_id here would half-introduce a tenancy model
   nothing else in the codebase supports.
2. Discord user ID columns are `String(32)` (matching `models.user.User.discord_id`)
   rather than Moo's raw `BigInteger` - these frequently need to compare
   against or reference User.discord_id, and mismatched types across that
   boundary would be its own class of bug.
"""
from __future__ import annotations

import enum
import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Enum, Float, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from database.engine import Base


class ReportStatus(str, enum.Enum):
    PENDING = "pending"
    AUTO_RESOLVED = "auto_resolved"  # dual review agreed, automated action taken
    ESCALATED = "escalated"  # low confidence or disagreement -> staff review required
    DISMISSED = "dismissed"


class RecommendedAction(str, enum.Enum):
    """The *only* actions the AI is ever allowed to recommend or auto-apply.

    There is deliberately no KICK/BAN/PERMISSION_CHANGE member here - those
    code paths do not exist anywhere in this domain. See
    services/ai/action_guard.py for the structural (not just schema-level)
    enforcement of the same boundary: even if this enum grew a member
    matching a real destructive+irreversible capability, action_guard would
    still block autonomous execution of it.
    """

    NONE = "none"
    WARN = "warn"
    DELETE_MESSAGE = "delete_message"
    TIMEOUT = "timeout"
    ESCALATE = "escalate"


class ModerationActionType(str, enum.Enum):
    """Every human-initiated moderation action, for the audit trail -
    deliberately broader than RecommendedAction (KICK/BAN included here,
    since a staff member can do those manually; the AI never can, and
    RecommendedAction's closed set enforces that separately)."""

    WARN = "warn"
    DELETE_MESSAGE = "delete_message"
    TIMEOUT = "timeout"
    UNTIMEOUT = "untimeout"
    KICK = "kick"
    BAN = "ban"


class ModerationAction(Base):
    """Audit record of every moderation action taken, human or AI-assisted.

    Phase 5 only *reads* this table (evidence-gathering in
    services/moderation_intelligence/service.py, repeat-offender checks) -
    nothing writes to it yet. The actual warn/timeout/kick/ban capabilities
    that would create these records need a live Discord connection
    (member.timeout(), etc.) that doesn't exist until Phase 6.
    """

    __tablename__ = "moderation_actions"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id: Mapped[str] = mapped_column(String(32), index=True)  # the moderated member
    moderator_id: Mapped[str] = mapped_column(String(32))  # who took the action ("ai" for AI-assisted)
    action_type: Mapped[ModerationActionType] = mapped_column(Enum(ModerationActionType))
    reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    duration_minutes: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class ModerationReport(Base):
    """A report of a member's behavior, either user-submitted (!report) or
    system-generated (spam/raid heuristics)."""

    __tablename__ = "moderation_reports"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    reported_user_id: Mapped[str] = mapped_column(String(32), index=True)
    # NULL reporter_id means the report was system-generated by a heuristic detector.
    reporter_id: Mapped[str | None] = mapped_column(String(32), nullable=True)
    channel_id: Mapped[str | None] = mapped_column(String(32), nullable=True)
    reported_message_id: Mapped[str | None] = mapped_column(String(32), nullable=True)
    reason: Mapped[str] = mapped_column(Text)
    source: Mapped[str] = mapped_column(String(50), default="user")  # "user" | "heuristic:spam" | ...
    status: Mapped[ReportStatus] = mapped_column(Enum(ReportStatus), default=ReportStatus.PENDING, index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class ModerationAnalysis(Base):
    """The AI's analysis of a ModerationReport, including dual-review outcome."""

    __tablename__ = "moderation_analyses"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    report_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("moderation_reports.id", ondelete="CASCADE"), index=True
    )
    risk_score: Mapped[float] = mapped_column(Float)
    confidence: Mapped[float] = mapped_column(Float)
    recommended_action: Mapped[RecommendedAction] = mapped_column(Enum(RecommendedAction))
    evidence_summary: Mapped[str] = mapped_column(Text)
    primary_model: Mapped[str] = mapped_column(String(150))
    secondary_model: Mapped[str | None] = mapped_column(String(150), nullable=True)
    agreement: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    action_taken: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class StaffEscalation(Base):
    """Anything the AI was not confident enough to resolve on its own,
    queued for a human. Shared across moderation, investigation, support,
    and (Phase 7) operational_intelligence - `source` distinguishes which
    domain raised it, matching Moo's original design rather than splitting
    into separate escalation tables per domain."""

    __tablename__ = "staff_escalations"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    source: Mapped[str] = mapped_column(String(50))  # "support" | "moderation" | "investigation" | "operational"
    related_report_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("moderation_reports.id", ondelete="SET NULL"), nullable=True
    )
    related_investigation_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    summary: Mapped[str] = mapped_column(Text)
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    resolved: Mapped[bool] = mapped_column(Boolean, default=False, index=True)
    resolved_by: Mapped[str | None] = mapped_column(String(32), nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    # Added for Phase 6's notification poller (umbrella-discord's
    # notifications_cog.py): NULL means "not yet announced to staff".
    # Tracked here, not in umbrella-discord, because all durable state in
    # this project lives in umbrella-core's DB - umbrella-discord itself
    # is stateless and could restart/redeploy at any time, which a local
    # "already posted" set would not survive.
    notified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
